<?php
$rnd_logos = array(
#	array('filename' => '00.png', 'title' => 'Logo by diver4d'),
	array('filename' => '01.png', 'title' => 'Logo by diver4d'),
#	array('filename' => '02.png', 'title' => 'Logo by PheeL'),
#	array('filename' => '03.png', 'title' => 'Logo by diver4d & AAA'),
	array('filename' => '04.png', 'title' => 'Logo by PheeL'),
	array('filename' => '05.png', 'title' => 'Logo by PheeL'),
	array('filename' => '06.gif', 'title' => 'Logo by PheeL', 'animated' => true),
	array('filename' => '07.png', 'title' => 'Logo by diver4d'),
	array('filename' => '08.gif', 'title' => 'Logo by nodeus', 'animated' => true),
	array('filename' => '09.png', 'title' => 'Logo by PheeL'),
#	array('filename' => '10.png', 'title' => 'Logo by Dimidrol'),
	array('filename' => '11.png', 'title' => 'Logo by diver4d'),
#	array('filename' => '12.png', 'title' => 'Logo by diver4d'),
#	array('filename' => '13.png', 'title' => 'Logo by diver4d'),
	array('filename' => '14.png', 'title' => 'Logo by diver4d'),
	array('filename' => '15.png', 'title' => 'Logo by diver4d'),
	array('filename' => '16.png', 'title' => 'Logo by diver4d'),
#	array('filename' => '17.gif', 'title' => 'Logo by nodeus', 'animated' => true),
#	array('filename' => '18.gif', 'title' => 'Logo by nodeus', 'animated' => true),
#	array('filename' => '19.png', 'title' => 'Logo by Dimidrol'),
	array('filename' => '20.png', 'title' => 'Logo by dman_pcb'),
	array('filename' => '21.png', 'title' => 'Logo by Tutty'),

	array('title' => 'dreamhyper by diver', 'filename' => 'hype-logo2/dreamhyper.png'),
	array('title' => 'stolen logo by diver', 'filename' => 'hype-logo2/stolenlogo2.png'),
	array('title' => 'hypey by diver', 'filename' => 'hype-logo2/hypey2.png'),
	array('title' => 'hycolor by diver', 'filename' => 'hype-logo2/hicolor.png'),
	array('title' => 'blocky by diver', 'filename' => 'hype-logo2/blocky3.png'),
	array('title' => 'icehype by diver', 'filename' => 'hype-logo2/hypespace.png'),
	array('title' => 'RGB by diver', 'filename' => 'hype-logo2/rgb.png'),
	array('title' => 'spectrum strings by diver', 'filename' => 'hype-logo2/strings.png'),
	array('title' => 'Design 3 by introspec', 'filename' => 'hype-logo2/hype_logo_3.png'),
	array('title' => 'history in the demomaking by diver', 'filename' => 'hype-logo2/hitdm.png'),
	array('title' => 'smooth by diver', 'filename' => 'hype-logo2/smooth.png'),
	array('title' => 'Design 1 by introspec', 'filename' => 'hype-logo2/hype_logo_1.png'),
	array('title' => 'stonecrash by diver', 'filename' => 'hype-logo2/stonecrash.png'),
	array('title' => 'Design 2 by introspec', 'filename' => 'hype-logo2/hype_logo_2.png'),
	array('title' => 'sub scribe by diver', 'filename' => 'hype-logo2/sub_scribe.png'),
	array('title' => 'be-be-be by diver', 'filename' => 'hype-logo2/bebebe.png'),
	array('title' => 'hypexolon by diver', 'filename' => 'hype-logo2/hypexolon_resampled.png'),
	array('title' => 'Hype <3 by diver', 'filename' => 'hype-logo2/IMG_2499.PNG'),
	array('title' => 'there is hype by diver', 'filename' => 'hype-logo2/there_is_hype.png'),
	array('title' => 'shifted by diver', 'filename' => 'hype-logo2/shifted.png'),
	array('title' => 'H+YP-E by diver', 'filename' => 'hype-logo2/plusYPminus.png'),
	array('title' => 'HYPÚ by diver', 'filename' => 'hype-logo2/IMG_2407.PNG'),
	array('title' => 'hypeboard by diver', 'filename' => 'hype-logo2/hypeboard.png'),
	array('title' => 'Subpixels by aturbidflow', 'filename' => 'hype-logo2/hype-gif-1.gif', 'animated' => true),
	array('title' => '53c by aturbidflow', 'filename' => 'hype-logo2/53cDrawing.png'),
	array('title' => 'hypr logo by dman', 'filename' => 'hype-logo2/hypr_logo.png'),
	array('title' => 'hope by diver', 'filename' => 'hype-logo2/hope.png'),
	array('title' => 'bloody spectrum by diver', 'filename' => 'hype-logo2/bloody spectrum.png'),
	array('title' => 'raznomast by diver', 'filename' => 'hype-logo2/raznomast.png'),
	array('title' => 'strype by diver', 'filename' => 'hype-logo2/strype.png'),
	array('title' => 'cracked by hype by dman', 'filename' => 'hype-logo2/cracked-by-hype.png'),
	array('title' => 'not kpss by diver', 'filename' => 'hype-logo2/IMG_2445.PNG'),
	array('title' => 'Battle City by aturbidflow', 'filename' => 'hype-logo2/HYPE-battlecity.png'),
	array('title' => 'oldschool_style by prof4d', 'filename' => 'hype-logo2/oldschool_style.png'),
	array('title' => 'HYPErodius by PheeL', 'filename' => 'hype-logo2/hyperodius.gif', 'animated' => true),

);	
